apiVersion: v1
kind: PersistentVolume
metadata:
  name: laravel-app-volume
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/www
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-app-pvc
  labels:
    name: laravel-app-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi