apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: default
  labels:
    name: mongo-service
spec:
  selector:
    app: mongo
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongo