language: bash

sudo: required

services:
  - docker
    
before_script:
  - apt-get install curl php-cli php-mbstring git unzip
  - curl -sS https://getcomposer.org/installer -o composer-setup.php
  - php composer-setup.php --install-dir=/usr/local/bin --filename=composer

script:
  - composer create-project "laravel/laravel" app --prefer-dist
  - cp -r app/* .
  - rm -rf app/
  - docker build . -t rennokki/lar8s:${TRAVIS_BUILD_ID}-${TRAVIS_BUILD_NUMBER}
  - docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
  - docker push rennokki/lar8s:${TRAVIS_BUILD_ID}-${TRAVIS_BUILD_NUMBER}
  - docker run rennokki/lar8s:${TRAVIS_BUILD_ID}-${TRAVIS_BUILD_NUMBER}
  - docker kill $(docker containers -aq)
  - docker build docker/php-fpm/ -t lar8s-php-fpm:${TRAVIS_BUILD_ID}-${TRAVIS_BUILD_NUMBER}
  - docker run rennokki/lar8s-php-fpm:${TRAVIS_BUILD_ID}-${TRAVIS_BUILD_NUMBER}
  - docker kill $(docker containers -aq)