kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-volume
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  labels:
    name: redis-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi