apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: laravel-horizon
  labels:
    app: laravel-horizon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-horizon
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: laravel-horizon
    spec:
      #imagePullSecrets:
      #  - name: "docker-registry-secrets"
      volumes:
        - name: laravel-app-volume
          emptyDir: {}
        - name: laravel-app-storage-persistent-volume
          persistentVolumeClaim:
            claimName: laravel-app-storage-pvc
      initContainers:
        - name: app
          image: <your_name>/<your_app_image>:<tag>
          command: ['/bin/sh', '-c', 'cp -rp /var/www/html/* /app/']
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - name: laravel-app-volume
              mountPath: /app
            - name: laravel-app-storage-persistent-volume
              mountPath: /app/storage
          envFrom:
            - secretRef:
                name: laravel-app-secrets
      containers:
        - name: horizon
          image: edbizarro/gitlab-ci-pipeline-php:7.2-fpm
          imagePullPolicy: Always
          command: ['php', 'artisan', 'horizon']
          resources:
            limits:
              cpu: 200m
              memory: 1536Mi
            requests:
              cpu: 200m
              memory: 1536Mi
          livenessProbe:
            exec:
              command: ['php', '-v']
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ['php', '-v']
            initialDelaySeconds: 3
            periodSeconds: 5
          volumeMounts:
            - name: laravel-app-volume
              mountPath: /var/www/html
            - name: laravel-app-storage-persistent-volume
              mountPath: /var/www/html/storage
          envFrom:
            - secretRef:
                name: laravel-app-secrets
