apiVersion: v1
kind: Service
metadata:
  name: pgsql-service
  namespace: default
  labels:
    name: pgsql-service
spec:
  selector:
    app: pgsql
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: pgsql